export const metadata = {
  title: "Terms of Service — Sunday",
};

// DRAFT — written to unblock Stripe account activation, which requires real
// (non-placeholder) terms covering subscription/cancellation. This has NOT
// been reviewed by counsel — see docs/business/DEPLOYMENT_AND_MARKETING.md
// A.12 for the full pre-public-launch legal gate this is one part of, and
// B.10 for the compliance-safe language rules this draft follows (never
// "advice", "recommends", etc.).

export default function TermsPage() {
  return (
    <div className="space-y-10 fade-up">
      <header className="space-y-3">
        <p className="label">Legal</p>
        <h1 className="font-sans text-3xl font-semibold tracking-tight text-ink sm:text-4xl">
          Terms of Service
        </h1>
        <p className="text-sm text-ink-subtle">Last updated: 4 July 2026 · Draft pending legal review</p>
      </header>

      <div className="max-w-prose space-y-8 text-base leading-relaxed text-ink-muted">
        <Section title="1. Acceptance">
          <p>
            By creating an account or using Sunday, you agree to these Terms and to our{" "}
            <a href="/privacy" className="text-accent hover:underline">
              Privacy Policy
            </a>
            . If you don&apos;t agree, don&apos;t use the service.
          </p>
        </Section>

        <Section title="2. What Sunday is — and isn't">
          <p>
            Sunday describes your portfolio: what changed, what it&apos;s worth, how it&apos;s
            allocated, and what that means in plain English. It is an{" "}
            <strong className="text-ink">information and education service</strong>.
          </p>
          <p>
            Sunday is <strong className="text-ink">not</strong> a financial adviser, broker, or
            portfolio manager, and nothing in the product — including anything generated by the AI
            assistant or the weekly briefing — is a recommendation to buy, sell, or hold any
            investment. We do not tell you what to do with your money. Decisions about your
            investments are yours alone, and you should seek independent, licensed financial advice
            before making them.
          </p>
        </Section>

        <Section title="3. Eligibility">
          <p>
            You must be at least 18 years old and legally able to enter into these Terms to use
            Sunday.
          </p>
        </Section>

        <Section title="4. Your account">
          <p>
            You&apos;re responsible for keeping access to your account secure — choose a strong,
            unique password, and consider enabling the authenticator-app two-factor option in
            Account settings. Never share your password or an active session with anyone else.
            Tell us immediately at{" "}
            <strong className="text-ink">hi@sundayfolio.com</strong> if you suspect unauthorised
            access.
          </p>
        </Section>

        <Section title="5. Plans, billing, and cancellation">
          <p>
            Sunday offers a <strong className="text-ink">Free</strong> plan and a paid{" "}
            <strong className="text-ink">Pro</strong> plan (currently €9/month), billed in advance
            through Stripe. Pro unlocks automatic weekly email delivery and live wallet/exchange
            sync, on top of everything in Free.
          </p>
          <ul className="list-disc space-y-1.5 pl-5">
            <li>Subscriptions renew automatically each billing period until cancelled.</li>
            <li>
              Cancel any time from the Billing page — you keep Pro access until the end of the
              period you&apos;ve already paid for, then drop to Free. No partial-period refunds.
            </li>
            <li>
              If we ever make a billing error, contact{" "}
              <strong className="text-ink">hi@sundayfolio.com</strong> and we&apos;ll correct
              it.
            </li>
            <li>Prices may change; we&apos;ll give existing subscribers notice before any increase applies to them.</li>
          </ul>
        </Section>

        <Section title="6. Acceptable use">
          <p>You agree not to:</p>
          <ul className="list-disc space-y-1.5 pl-5">
            <li>Use Sunday for any unlawful purpose</li>
            <li>Attempt to access another user&apos;s account or data</li>
            <li>Probe, scan, or attempt to bypass the security of the service</li>
            <li>Scrape or systematically extract data from the service</li>
            <li>Misrepresent AI-generated content in the briefing or chat as independent financial advice to a third party</li>
          </ul>
        </Section>

        <Section title="7. Your data">
          <p>
            You own the portfolio data you provide. We use it only to operate the service, as
            described in our{" "}
            <a href="/privacy" className="text-accent hover:underline">
              Privacy Policy
            </a>
            .
          </p>
        </Section>

        <Section title="8. Intellectual property">
          <p>
            The Sunday product, design, and underlying software are our property or licensed to us.
            These Terms don&apos;t grant you any rights to our trademarks, branding, or code.
          </p>
        </Section>

        <Section title="9. Disclaimers">
          <p>
            Sunday is provided &quot;as is.&quot; Prices, tax figures, and projections are computed
            deterministically from the data you provide and third-party market data, which can be
            delayed, incomplete, or wrong. Narrative sections are generated with AI assistance and
            may occasionally be inaccurate. Always verify figures independently before relying on
            them, and never treat anything in Sunday as a substitute for professional financial or
            tax advice.
          </p>
        </Section>

        <Section title="10. Limitation of liability">
          <p>
            To the maximum extent permitted by law, Sunday is not liable for any investment losses,
            missed gains, or financial decisions you make based on information in the product. Our
            total liability for any claim relating to the service is limited to the amount you paid
            us in the 12 months before the claim arose.
          </p>
        </Section>

        <Section title="11. Termination">
          <p>
            You can close your account at any time. We may suspend or close an account that
            violates these Terms, or that we reasonably believe poses a security or legal risk to
            us or other users.
          </p>
        </Section>

        <Section title="12. Governing law">
          <p>
            These Terms are governed by the laws of Portugal, without regard to conflict-of-law
            principles. If you are an EU consumer, mandatory consumer-protection laws of your
            country of residence also apply and take precedence where they conflict with this
            clause.
          </p>
        </Section>

        <Section title="13. Changes to these terms">
          <p>
            We may update these Terms as the product evolves. We&apos;ll notify you by email before
            material changes take effect; continued use after that point means you accept the
            updated Terms.
          </p>
        </Section>

        <Section title="14. Contact">
          <p>
            Questions about these Terms: <strong className="text-ink">hi@sundayfolio.com</strong>.
          </p>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="font-sans text-xl font-semibold tracking-tight text-ink">{title}</h2>
      {children}
    </section>
  );
}
